# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      team_name:
        description: 'Team name, will be used to create policy, role and KV store'
        required: true
      azure_object_id:
        description: 'Object ID for Azure AD group, will be used to create Vault group and alias'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  lil-echo:
    runs-on: ubuntu-latest
    env:
      team_name: '${{ github.event.inputs.team_name }}'
      azure_object_id: '${{ github.event.inputs.azure_object_id }}'
    steps:
    - name: Test input pars
      run: |
        echo "Team name is $team_name and Azure object id is $azure_object_id"

  # replace this with a call to vault admin app 

  curl-it:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://example.com/api/v2/endpoint"
#        curl \
#  -X POST \
#  -H "Accept: application/vnd.github+json" \
#  -H "Authorization: Bearer <YOUR-TOKEN>"\
#  -H "X-GitHub-Api-Version: 2022-11-28" \
#  https://api.github.com/repos/OWNER/REPO/issues \
#  -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'

