on: 
  workflow_dispatch:
    inputs: 
      team_name:
        description: 'Team name, will be used to create policy, role and KV store'
        required: true
      azure_object_id:
        description: 'Azure AD group object ID, used for Vault group alias'
        required: true


name: Create an issue
permissions:
  contents: read
  issues: write 
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEAM: ${{ github.event.inputs.team_name }}
          OBJECT_ID: ${{ github.event.inputs.azure_object_id }}
        with:
          filename: .github/ISSUE_TEMPLATE/vault-onboarding-for-team--team-.md
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
  # this should be conditional
  call-vault-admin:
    if: ${{ steps.create-issue.outputs.number }} != null
    runs-on: ubuntu-latest
    steps:
      - name: Call Vault Admin
        env:
          TEAM: ${{ github.event.inputs.team_name }}
          OBJECT_ID: ${{ github.event.inputs.azure_object_id }}
          ISSUE_URL: ${{ steps.create-issue.outputs.url }} # do we need to pass this to vault admin? can close it in another action?
      - run: 'echo URL: $ISSUE_URL'   
      - run: |
          curl -X GET "https://example.com/api/v2/endpoint
#      - run: |
#          curl -X POST "https://vauld-admin.rdswf.net/teams -d '{ "team": "$TEAM", "objectId": "$OBJECT_ID", "url": "${{ steps.create-issue.outputs.url }}"}'
#      - run: echo "{status}={??}" >> $GITHUB_OUTPUT

